# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: oliver.copping@diamond.ac.uk
author_name: Oliver Copping
component_owner: group:default/sscc
description: A package for building GUIs
distribution_name: phoebus-guibuilder
docker: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: phoebus_guibuilder
pypi: false
repo_name: phoebus-guibuilder
type_checker: pyright
