[tool.poetry]
name = "guibuilder"
version = "0.1.0"
description = "A package for building GUIs"
authors = ["Oliver Copping <oliver.copping@diamond.ac.uk>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"