name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        if [ $PYTHON_VERSION == "dev" ]; then
          PYTHON_VERSION=$(sed -n "s/ARG PYTHON_VERSION=//p" Dockerfile)
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: pdm sync -d -G dev
      shell: bash

    - name: Report what was installed
      run: pdm list
      shell: bash

    - name: Add venv path to Github environment
      run: echo "VENV_PATH=$(pdm venv activate | sed 's/.*source //; s|/bin/activate||')" >> $GITHUB_ENV
      shell: bash

    - name: Add venv path to Github Path
      run: echo "${{ env.VENV_PATH }}/bin:$PATH" >> $GITHUB_PATH
      shell: bash
