name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"
  poetry-version:
    description: Poetry version to install, from pyproject.toml
    default: $(yq '.project."optional-dependencies".dev[] | select(. | contains("poetry"))' pyproject.toml | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        if [ $PYTHON_VERSION == "dev" ]; then
          PYTHON_VERSION=$(sed -n "s/ARG PYTHON_VERSION=//p" Dockerfile)
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ inputs.poetry-version }}

    # - name: Install Poetry with specific version from pyproject.toml
    #   uses: snok/install-poetry@v1
    #   with:
    #     poetry-version-from-pyproject-toml: true

    - name: Install dependencies
      run: poetry install --no-root
      shell: bash

    - name: Report what was installed
      run: poetry show
      shell: bash
